// Code generated by the Encore v1.52.3 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-purelivingpro-ed2i.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the purelivingpro-ed2i Encore application.
 */
export default class Client {
    public readonly affiliate: affiliate.ServiceClient
    public readonly ai: ai.ServiceClient
    public readonly analytics: analytics.ServiceClient
    public readonly auth: auth.ServiceClient
    public readonly automation: automation.ServiceClient
    public readonly content: content.ServiceClient
    public readonly frontend: frontend.ServiceClient
    public readonly newsletter: newsletter.ServiceClient
    public readonly seo: seo.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.affiliate = new affiliate.ServiceClient(base)
        this.ai = new ai.ServiceClient(base)
        this.analytics = new analytics.ServiceClient(base)
        this.auth = new auth.ServiceClient(base)
        this.automation = new automation.ServiceClient(base)
        this.content = new content.ServiceClient(base)
        this.frontend = new frontend.ServiceClient(base)
        this.newsletter = new newsletter.ServiceClient(base)
        this.seo = new seo.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: auth.AuthParams | AuthDataGenerator
}

export namespace affiliate {
    export interface AffiliateLink {
        id: number
        productId: number
        shortCode: string
        originalUrl: string
        trackingParams?: { [key: string]: any }
        isActive: boolean
        createdAt: string
    }

    export interface AffiliateProduct {
        id: number
        programId: number
        name: string
        slug: string
        description?: string
        price?: number
        originalUrl: string
        imageUrl?: string
        category?: string
        tags?: string[]
        isActive: boolean
        createdAt: string
        updatedAt: string
        program?: {
            name: string
            commissionRate: number
        }
    }

    export interface AffiliateProgram {
        id: number
        name: string
        description?: string
        commissionRate: number
        cookieDuration: number
        trackingDomain?: string
        isActive: boolean
        createdAt: string
        updatedAt: string
    }

    export interface AffiliateStats {
        totalClicks: number
        totalConversions: number
        totalCommission: number
        conversionRate: number
        topProducts: {
            productId: number
            productName: string
            clicks: number
            conversions: number
            commission: number
        }[]
        clicksByDay: {
            date: string
            clicks: number
        }[]
        deviceBreakdown: {
            deviceType: string
            clicks: number
            percentage: number
        }[]
    }

    export interface CreateAffiliateLinkRequest {
        productId: number
        originalUrl: string
        trackingParams?: { [key: string]: any }
    }

    export interface CreateAffiliateProductRequest {
        programId: number
        name: string
        slug: string
        description?: string
        price?: number
        originalUrl: string
        imageUrl?: string
        category?: string
        tags?: string[]
        isActive?: boolean
    }

    export interface CreateAffiliateProgramRequest {
        name: string
        description?: string
        commissionRate: number
        cookieDuration?: number
        trackingDomain?: string
        isActive?: boolean
    }

    export interface ListAffiliateProductsRequest {
        limit?: number
        offset?: number
        category?: string
        programId?: number
        search?: string
    }

    export interface ListAffiliateProductsResponse {
        products: AffiliateProduct[]
        total: number
    }

    export interface ListAffiliateProgramsResponse {
        programs: AffiliateProgram[]
    }

    export interface RedirectResponse {
        redirectUrl: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createAffiliateLink = this.createAffiliateLink.bind(this)
            this.createProduct = this.createProduct.bind(this)
            this.createProgram = this.createProgram.bind(this)
            this.deleteProduct = this.deleteProduct.bind(this)
            this.getAffiliateStats = this.getAffiliateStats.bind(this)
            this.getProduct = this.getProduct.bind(this)
            this.handleRedirect = this.handleRedirect.bind(this)
            this.listAffiliateProducts = this.listAffiliateProducts.bind(this)
            this.listPrograms = this.listPrograms.bind(this)
            this.updateProduct = this.updateProduct.bind(this)
        }

        /**
         * Creates a new affiliate tracking link.
         */
        public async createAffiliateLink(params: CreateAffiliateLinkRequest): Promise<AffiliateLink> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/affiliate/links`, JSON.stringify(params))
            return await resp.json() as AffiliateLink
        }

        /**
         * Creates a new affiliate product.
         */
        public async createProduct(params: CreateAffiliateProductRequest): Promise<AffiliateProduct> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/affiliate/products`, JSON.stringify(params))
            return await resp.json() as AffiliateProduct
        }

        /**
         * Creates a new affiliate program.
         */
        public async createProgram(params: CreateAffiliateProgramRequest): Promise<AffiliateProgram> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/affiliate/programs`, JSON.stringify(params))
            return await resp.json() as AffiliateProgram
        }

        /**
         * Deletes an affiliate product.
         */
        public async deleteProduct(id: number): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/affiliate/products/${encodeURIComponent(id)}`)
        }

        /**
         * Retrieves comprehensive affiliate marketing statistics.
         */
        public async getAffiliateStats(): Promise<AffiliateStats> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/affiliate/stats`)
            return await resp.json() as AffiliateStats
        }

        /**
         * Retrieves a single affiliate product by its slug (URL-friendly identifier).
         */
        public async getProduct(slug: string): Promise<AffiliateProduct> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/affiliate/products/by-slug/${encodeURIComponent(slug)}`)
            return await resp.json() as AffiliateProduct
        }

        /**
         * Handles affiliate link redirects with tracking (matches /r/:id pattern from original architecture).
         */
        public async handleRedirect(shortCode: string, params: {
    contentId?: string
    sessionId?: string
    userAgent?: string
    xForwardedFor?: string
    referrer?: string
}): Promise<RedirectResponse> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                referer:           params.referrer,
                "user-agent":      params.userAgent,
                "x-forwarded-for": params.xForwardedFor,
            })

            const query = makeRecord<string, string | string[]>({
                contentId: params.contentId,
                sessionId: params.sessionId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/r/${encodeURIComponent(shortCode)}`, undefined, {headers, query})
            return await resp.json() as RedirectResponse
        }

        /**
         * Retrieves affiliate products with optional filtering.
         */
        public async listAffiliateProducts(params: ListAffiliateProductsRequest): Promise<ListAffiliateProductsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                category:  params.category,
                limit:     params.limit === undefined ? undefined : String(params.limit),
                offset:    params.offset === undefined ? undefined : String(params.offset),
                programId: params.programId === undefined ? undefined : String(params.programId),
                search:    params.search,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/affiliate/products`, undefined, {query})
            return await resp.json() as ListAffiliateProductsResponse
        }

        /**
         * Retrieves all affiliate programs.
         */
        public async listPrograms(): Promise<ListAffiliateProgramsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/affiliate/programs`)
            return await resp.json() as ListAffiliateProgramsResponse
        }

        /**
         * Updates an existing affiliate product.
         */
        public async updateProduct(id: number, params: {
    programId?: number
    name?: string
    slug?: string
    description?: string
    price?: number
    originalUrl?: string
    imageUrl?: string
    category?: string
    tags?: string[]
    isActive?: boolean
}): Promise<AffiliateProduct> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/affiliate/products/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as AffiliateProduct
        }
    }
}

export namespace ai {
    export interface ChatRequest {
        message: string
        sessionId: string
        context?: string
    }

    export interface ChatResponse {
        response: string
        recommendations?: {
            productId: number
            reason: string
        }[]
    }

    export interface RecommendationRequest {
        userInput: string
        preferences?: {
            budget?: string
            category?: string
            goals?: string[]
        }
    }

    export interface RecommendationResponse {
        recommendations: {
            product: {
                id: number
                name: string
                slug: string
                description?: string
                price?: number
                imageUrl?: string
                affiliateUrl: string
            }
            reason: string
            confidenceScore: number
        }[]
        explanation: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.chatAssistant = this.chatAssistant.bind(this)
            this.getProductRecommendations = this.getProductRecommendations.bind(this)
        }

        /**
         * AI-powered health and wellness chat assistant.
         */
        public async chatAssistant(params: ChatRequest): Promise<ChatResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/ai/chat`, JSON.stringify(params))
            return await resp.json() as ChatResponse
        }

        /**
         * AI-powered product recommendations based on user input and preferences.
         */
        public async getProductRecommendations(params: RecommendationRequest): Promise<RecommendationResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/ai/recommendations`, JSON.stringify(params))
            return await resp.json() as RecommendationResponse
        }
    }
}

export namespace analytics {
    export interface AnalyticsSummary {
        totalPageViews: number
        totalSearches: number
        topSearchQueries: {
            query: string
            count: number
        }[]
        popularPages: {
            path: string
            views: number
        }[]
        recentActivity: {
            pageViewsToday: number
            searchesToday: number
            pageViewsThisWeek: number
            searchesThisWeek: number
        }
    }

    export interface ClickStats {
        totalClicks: number
        uniqueClicks: number
        ctr: number
        avgRedirectTime: number
        topProducts: ProductStats[]
        topPages: PageStats[]
        timeSeries: TimeSeriesPoint[]
    }

    export interface ExportClicksRequest {
        startDate?: string
        endDate?: string
        productId?: number
        contentId?: string
        category?: string
        utmSource?: string
        utmMedium?: string
        format?: "csv" | "json"
        limit?: number
    }

    export interface ExportClicksResponse {
        downloadUrl: string
        filename: string
        recordCount: number
    }

    export interface GetClickStatsRequest {
        productId?: number
        contentId?: string
        category?: string
        startDate?: string
        endDate?: string
        utmSource?: string
        utmMedium?: string
        utmCampaign?: string
        device?: string
        limit?: number
        offset?: number
    }

    export interface PageStats {
        pagePath: string
        clicks: number
        uniqueClicks: number
        ctr: number
    }

    export interface ProductStats {
        productId: number
        productName: string
        clicks: number
        uniqueClicks: number
        ctr: number
        avgRedirectTime: number
    }

    export interface TimeSeriesPoint {
        timestamp: string
        clicks: number
        uniqueClicks: number
        ctr?: number
        avgRedirectTime?: number
    }

    export interface TrackClickRequest {
        linkId: number
        productId: number
        contentId?: string
        pickId?: string
        variantId?: string
        pagePath?: string
        referrer?: string
        utmSource?: string
        utmMedium?: string
        utmCampaign?: string
        utmTerm?: string
        utmContent?: string
        device?: string
        country?: string
        browser?: string
        redirectMs?: number
        success?: boolean
    }

    export interface TrackClickResponse {
        eventId: string
        success: boolean
    }

    export interface TrackPageViewRequest {
        articleId?: number
        pagePath: string
        referrer?: string
        sessionId?: string
        userAgent?: string
        xForwardedFor?: string
    }

    export interface TrackSearchRequest {
        query: string
        resultsCount: number
        sessionId?: string
        userAgent?: string
        xForwardedFor?: string
    }

    export interface UnifiedDashboardData {
        overview: {
            totalPageViews: number
            totalRevenue: number
            totalArticles: number
            totalAffiliateClicks: number
            conversionRate: number
            revenueGrowth: number
            trafficGrowth: number
        }
        contentPerformance: {
            publishedToday: number
            publishedThisWeek: number
            publishedThisMonth: number
            topPerformingArticles: {
                id: number
                title: string
                viewCount: number
                revenue: number
                publishedAt: string
            }[]
            contentByCategory: {
                category: string
                count: number
                views: number
            }[]
        }
        affiliateRevenue: {
            dailyRevenue: {
                date: string
                revenue: number
                clicks: number
                conversions: number
            }[]
            topProducts: {
                productId: number
                productName: string
                revenue: number
                clicks: number
                conversions: number
                conversionRate: number
            }[]
            monthlyTrend: {
                currentMonth: number
                previousMonth: number
                growth: number
            }
        }
        automationStatus: {
            activePipelineJobs: number
            completedToday: number
            failedJobs: number
            upcomingScheduled: number
            recentActivity: {
                id: number
                topic: string
                status: string
                createdAt: string
                scheduledAt?: string
            }[]
            linkHealthSummary: {
                totalLinks: number
                workingLinks: number
                brokenLinks: number
                lastChecked: string | null
            }
        }
        trafficAnalytics: {
            pageViewsTrend: {
                date: string
                views: number
                uniqueVisitors: number
            }[]
            topPages: {
                path: string
                views: number
                bounceRate: number
                avgTimeOnPage: number
            }[]
            trafficSources: {
                source: string
                visitors: number
                percentage: number
            }[]
            deviceBreakdown: {
                device: string
                visitors: number
                percentage: number
            }[]
        }
        aiInsights: {
            recommendationAccuracy: number
            totalRecommendationsServed: number
            userEngagementRate: number
            topRecommendedProducts: {
                productName: string
                recommendationCount: number
                clickThrough: number
            }[]
        }
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.exportClicksCSV = this.exportClicksCSV.bind(this)
            this.getAnalyticsSummary = this.getAnalyticsSummary.bind(this)
            this.getClickStats = this.getClickStats.bind(this)
            this.getRetryQueueStatus = this.getRetryQueueStatus.bind(this)
            this.getUnifiedDashboard = this.getUnifiedDashboard.bind(this)
            this.trackClick = this.trackClick.bind(this)
            this.trackPageView = this.trackPageView.bind(this)
            this.trackSearch = this.trackSearch.bind(this)
            this.triggerRetryQueueProcessing = this.triggerRetryQueueProcessing.bind(this)
        }

        /**
         * Exports click data as CSV with filtering and pagination support
         */
        public async exportClicksCSV(params: ExportClicksRequest): Promise<ExportClicksResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                category:  params.category,
                contentId: params.contentId,
                endDate:   params.endDate,
                format:    params.format === undefined ? undefined : String(params.format),
                limit:     params.limit === undefined ? undefined : String(params.limit),
                productId: params.productId === undefined ? undefined : String(params.productId),
                startDate: params.startDate,
                utmMedium: params.utmMedium,
                utmSource: params.utmSource,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/export-clicks`, undefined, {query})
            return await resp.json() as ExportClicksResponse
        }

        /**
         * Retrieves analytics summary data for the admin dashboard.
         */
        public async getAnalyticsSummary(): Promise<AnalyticsSummary> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/analytics/summary`)
            return await resp.json() as AnalyticsSummary
        }

        /**
         * Retrieves comprehensive click statistics with filtering and time series data
         */
        public async getClickStats(params: GetClickStatsRequest): Promise<ClickStats> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                category:    params.category,
                contentId:   params.contentId,
                device:      params.device,
                endDate:     params.endDate,
                limit:       params.limit === undefined ? undefined : String(params.limit),
                offset:      params.offset === undefined ? undefined : String(params.offset),
                productId:   params.productId === undefined ? undefined : String(params.productId),
                startDate:   params.startDate,
                utmCampaign: params.utmCampaign,
                utmMedium:   params.utmMedium,
                utmSource:   params.utmSource,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/click-stats`, undefined, {query})
            return await resp.json() as ClickStats
        }

        /**
         * Get retry queue status
         */
        public async getRetryQueueStatus(): Promise<{
    pendingItems: number
    processedItems: number
    failedItems: number
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/retry-queue-status`)
            return await resp.json() as {
    pendingItems: number
    processedItems: number
    failedItems: number
}
        }

        public async getUnifiedDashboard(): Promise<UnifiedDashboardData> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/analytics/unified-dashboard`)
            return await resp.json() as UnifiedDashboardData
        }

        /**
         * Validates and ingests affiliate click events with comprehensive tracking data
         */
        public async trackClick(params: TrackClickRequest): Promise<TrackClickResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/track-click`, JSON.stringify(params))
            return await resp.json() as TrackClickResponse
        }

        /**
         * Tracks a page view for analytics purposes.
         */
        public async trackPageView(params: TrackPageViewRequest): Promise<void> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                "user-agent":      params.userAgent,
                "x-forwarded-for": params.xForwardedFor,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                articleId: params.articleId,
                pagePath:  params.pagePath,
                referrer:  params.referrer,
                sessionId: params.sessionId,
            }

            await this.baseClient.callTypedAPI("POST", `/analytics/page-view`, JSON.stringify(body), {headers})
        }

        /**
         * Tracks a search query for analytics purposes.
         */
        public async trackSearch(params: TrackSearchRequest): Promise<void> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                "user-agent":      params.userAgent,
                "x-forwarded-for": params.xForwardedFor,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                query:        params.query,
                resultsCount: params.resultsCount,
                sessionId:    params.sessionId,
            }

            await this.baseClient.callTypedAPI("POST", `/analytics/search`, JSON.stringify(body), {headers})
        }

        /**
         * Manual API endpoint to trigger retry queue processing (for testing/debugging)
         */
        public async triggerRetryQueueProcessing(): Promise<{
    message: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/trigger-retry-processing`)
            return await resp.json() as {
    message: string
}
        }
    }
}

export namespace auth {
    export interface AuthParams {
        authorization: string
    }

    export interface LoginRequest {
        email: string
        password: string
    }

    export interface LoginResponse {
        token: string
        user: User
        expiresAt: string
    }

    export interface User {
        id: number
        email: string
        role: UserRole
        name?: string
        isActive: boolean
        createdAt: string
        updatedAt: string
        lastLoginAt?: string
    }

    export type UserRole = "admin" | "editor" | "viewer"

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.login = this.login.bind(this)
            this.me = this.me.bind(this)
        }

        /**
         * Login endpoint - authenticates user and returns JWT token
         */
        public async login(params: LoginRequest): Promise<LoginResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/auth/login`, JSON.stringify(params))
            return await resp.json() as LoginResponse
        }

        /**
         * Get current user endpoint - requires authentication
         */
        public async me(): Promise<User> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/auth/me`)
            return await resp.json() as User
        }
    }
}

export namespace automation {
    export interface AmazonProduct {
        asin: string
        title: string
        price?: number
        imageUrl?: string
        description?: string
        category?: string
        rating?: number
        reviewCount?: number
    }

    export interface AutomationSchedule {
        id: number
        name: string
        type: string
        cronExpression: string
        isActive: boolean
        lastRun?: string
        nextRun?: string
        config: any
    }

    export interface BulkKeywordTrackingRequest {
        keywords: {
            keyword: string
            targetUrl: string
            targetRank?: number
        }[]
    }

    export interface BulkOptimizationRequest {
        articleIds: number[]
        optimizationType: "seo" | "affiliate" | "engagement" | "conversion"
        batchSize?: number
    }

    export interface BulkOptimizationResponse {
        totalArticles: number
        optimized: number
        failed: number
        estimatedRevenueIncrease: number
        optimizationResults: {
            articleId: number
            title: string
            success: boolean
            improvements: any
        }[]
    }

    export interface ContentOptimizationRequest {
        articleId: number
        optimizationType: "seo" | "affiliate" | "engagement" | "conversion"
        targetKeywords?: string[]
        targetProducts?: number[]
    }

    export interface ContentPipelineRequest {
        topics: string[]
        autoPublish?: boolean
        platforms?: ("medium" | "wordpress")[]
        includeAffiliateProducts?: boolean
    }

    export interface ContentPipelineResponse {
        totalTopics: number
        successful: number
        failed: number
        results: PipelineResult[]
    }

    export interface CreateScheduleResponse {
        id: number
        nextRun: string
    }

    export interface GenerateContentRequest {
        topic: string
        targetKeywords: string[]
        includeAffiliateProducts?: boolean
    }

    export interface GenerateSocialContentRequest {
        articleId: number
        platforms: string[]
    }

    export interface GenerateSocialContentResponse {
        posts: SocialMediaPost[]
    }

    export interface GeneratedContent {
        title: string
        content: string
        excerpt: string
        seoScore: number
        suggestedProducts: {
            id: number
            placement: string
            reason: string
        }[]
    }

    export interface GetScheduleResponse {
        scheduledContent: ScheduledContent[]
        totalScheduled: number
        nextPublishDate?: string
    }

    export interface GetSchedulesResponse {
        schedules: AutomationSchedule[]
    }

    export interface ImplementOptimizationsRequest {
        contentOptimizations: number[]
        affiliateOptimizations: number[]
        keywordTargets: string[]
    }

    export interface IngestFromSheetsRequest {
        spreadsheetId: string
        range?: string
    }

    export interface IngestFromSheetsResponse {
        processed: number
        ingested: number
        errors: string[]
    }

    export interface LinkHealthReport {
        totalLinks: number
        workingLinks: number
        brokenLinks: number
        slowLinks: number
        recentlyFixed: number
    }

    export interface OptimizationReport {
        contentOptimizations: {
            articleId: number
            title: string
            currentRevenue: number
            potentialRevenue: number
            recommendations: string[]
        }[]
        affiliateOptimizations: {
            productId: number
            productName: string
            currentCTR: number
            recommendedActions: string[]
        }[]
        keywordOpportunities: {
            keyword: string
            searchVolume: number
            difficulty: number
            potentialRevenue: number
        }[]
        totalPotentialIncrease: number
    }

    export interface OptimizedContent {
        originalTitle: string
        optimizedTitle: string
        originalContent: string
        optimizedContent: string
        optimizationSummary: string
        estimatedImprovements: {
            seoScore: number
            affiliateIntegration: number
            readabilityScore: number
            conversionPotential: number
        }
        suggestedProducts: {
            productId: number
            productName: string
            placement: string
            reason: string
        }[]
    }

    export interface PipelineResult {
        topic: string
        articleId?: number
        generationStatus: "success" | "failed"
        optimizationStatus: "success" | "failed" | "skipped"
        publishingStatus: {
            medium?: "success" | "failed" | "skipped"
            wordpress?: "success" | "failed" | "skipped"
        }
        errors: string[]
    }

    export interface ProductSearchRequest {
        keywords: string
        category?: string
        maxResults?: number
    }

    export interface ProductSyncResponse {
        searched: number
        found: number
        imported: number
        updated: number
        errors: string[]
    }

    export interface PublishPostsResponse {
        published: number
        failed: number
    }

    export interface RevenueOptimizationReport {
        currentMonthRevenue: number
        projectedMonthlyRevenue: number
        topPerformingProducts: {
            productId: number
            productName: string
            clicks: number
            conversions: number
            revenue: number
            conversionRate: number
        }[]
        underperformingProducts: {
            productId: number
            productName: string
            clicks: number
            conversions: number
            suggestions: string[]
        }[]
        optimizationActions: string[]
    }

    export interface RunTasksResponse {
        executed: number
        failed: number
    }

    export interface SEOMetrics {
        keyword: string
        currentRank: number
        previousRank?: number
        searchVolume: number
        difficulty: number
        url: string
        lastUpdated: string
    }

    export interface SEOReport {
        totalKeywords: number
        averageRank: number
        rankImprovements: number
        rankDeclines: number
        topKeywords: SEOMetrics[]
        opportunityKeywords: SEOMetrics[]
        competitorAnalysis: {
            competitor: string
            averageRank: number
            sharedKeywords: number
        }[]
    }

    export interface ScheduleConfig {
        name: string
        type: "content_generation" | "link_check" | "social_posting" | "analytics_report"
        cronExpression: string
        config: { [key: string]: any }
        isActive?: boolean
    }

    export interface ScheduleContentRequest {
        topic: string
        targetKeywords: string[]
        publishDate: string
        includeAffiliateProducts: boolean
        socialPlatforms: string[]
    }

    export interface ScheduledContent {
        id: number
        topic: string
        status: string
        scheduledAt: string
        generatedTitle?: string
        estimatedRevenue: number
    }

    export interface SearchProductsResponse {
        products: AmazonProduct[]
    }

    export interface SecretTestResult {
        service: string
        status: "success" | "error" | "not_configured"
        message: string
        details?: any
    }

    export interface SecretsTestResponse {
        results: SecretTestResult[]
        "overall_status": "all_good" | "some_issues" | "major_issues"
        "tested_at": string
    }

    export interface SocialMediaPost {
        platform: string
        content: string
        hashtags: string[]
        mediaUrls?: string[]
        scheduledAt: string
    }

    export interface TrackKeywordRequest {
        keyword: string
        targetUrl: string
        targetRank?: number
        searchVolume?: number
        difficulty?: number
    }

    export interface WeeklyDigestResponse {
        emailSent: boolean
        reportData: {
            period: {
                start: string
                end: string
            }
            content: {
                articlesPublished: number
                totalViews: number
                topArticle: {
                    title: string
                    views: number
                    slug: string
                }
            }
            affiliate: {
                totalClicks: number
                totalRevenue: number
                conversionRate: number
                topProduct: {
                    name: string
                    revenue: number
                    clicks: number
                }
            }
            recommendations: string[]
        }
    }

    export interface WeeklyReport {
        period: {
            start: string
            end: string
        }
        revenue: {
            total: number
            target: number
            percentageOfTarget: number
            projectedMonthly: number
        }
        content: {
            articlesPublished: number
            totalViews: number
            topPerformingArticle: {
                title: string
                views: number
                slug: string
            }
        }
        affiliate: {
            totalClicks: number
            conversions: number
            conversionRate: number
            topProduct: {
                name: string
                revenue: number
                clicks: number
            }
        }
        automation: {
            tasksExecuted: number
            contentGenerated: number
            socialPostsPublished: number
            linksChecked: number
        }
        recommendations: string[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.analyzePerformance = this.analyzePerformance.bind(this)
            this.analyzeRevenue = this.analyzeRevenue.bind(this)
            this.bulkOptimizeContent = this.bulkOptimizeContent.bind(this)
            this.bulkTrackKeywords = this.bulkTrackKeywords.bind(this)
            this.checkAffiliateLinks = this.checkAffiliateLinks.bind(this)
            this.createSchedule = this.createSchedule.bind(this)
            this.discoverKeywordOpportunities = this.discoverKeywordOpportunities.bind(this)
            this.enhanceContentWithProducts = this.enhanceContentWithProducts.bind(this)
            this.generateContent = this.generateContent.bind(this)
            this.generateSEOReport = this.generateSEOReport.bind(this)
            this.generateSocialContent = this.generateSocialContent.bind(this)
            this.generateWeeklyDigest = this.generateWeeklyDigest.bind(this)
            this.generateWeeklyReport = this.generateWeeklyReport.bind(this)
            this.getContentSchedule = this.getContentSchedule.bind(this)
            this.getLinkHealthReport = this.getLinkHealthReport.bind(this)
            this.getSchedules = this.getSchedules.bind(this)
            this.identifyOptimizationTargets = this.identifyOptimizationTargets.bind(this)
            this.implementOptimizations = this.implementOptimizations.bind(this)
            this.implementRevenueOptimizations = this.implementRevenueOptimizations.bind(this)
            this.ingestFromSheets = this.ingestFromSheets.bind(this)
            this.optimizeArticleContent = this.optimizeArticleContent.bind(this)
            this.processScheduledContent = this.processScheduledContent.bind(this)
            this.publishScheduledPosts = this.publishScheduledPosts.bind(this)
            this.runContentPipeline = this.runContentPipeline.bind(this)
            this.runScheduledTasks = this.runScheduledTasks.bind(this)
            this.scheduleContent = this.scheduleContent.bind(this)
            this.scheduleContentGeneration = this.scheduleContentGeneration.bind(this)
            this.searchAmazonProducts = this.searchAmazonProducts.bind(this)
            this.sendWeeklyReport = this.sendWeeklyReport.bind(this)
            this.syncAmazonProducts = this.syncAmazonProducts.bind(this)
            this.testSecrets = this.testSecrets.bind(this)
            this.trackKeyword = this.trackKeyword.bind(this)
            this.updateKeywordRankings = this.updateKeywordRankings.bind(this)
        }

        /**
         * Analyzes performance and generates optimization recommendations.
         */
        public async analyzePerformance(): Promise<OptimizationReport> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/automation/performance-analysis`)
            return await resp.json() as OptimizationReport
        }

        /**
         * Analyzes affiliate performance and suggests optimizations.
         */
        public async analyzeRevenue(): Promise<RevenueOptimizationReport> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/automation/revenue-analysis`)
            return await resp.json() as RevenueOptimizationReport
        }

        /**
         * Optimizes multiple articles in batch for efficiency.
         */
        public async bulkOptimizeContent(params: BulkOptimizationRequest): Promise<BulkOptimizationResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/bulk-optimize`, JSON.stringify(params))
            return await resp.json() as BulkOptimizationResponse
        }

        /**
         * Tracks multiple keywords in bulk for efficiency.
         */
        public async bulkTrackKeywords(params: BulkKeywordTrackingRequest): Promise<{
    added: number
    updated: number
    failed: number
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/bulk-track-keywords`, JSON.stringify(params))
            return await resp.json() as {
    added: number
    updated: number
    failed: number
}
        }

        /**
         * Checks all affiliate links for availability and performance.
         */
        public async checkAffiliateLinks(): Promise<LinkHealthReport> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/check-links`)
            return await resp.json() as LinkHealthReport
        }

        /**
         * Creates or updates an automation schedule.
         */
        public async createSchedule(params: ScheduleConfig): Promise<CreateScheduleResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/schedule`, JSON.stringify(params))
            return await resp.json() as CreateScheduleResponse
        }

        /**
         * Automatically discovers keyword opportunities from existing content.
         */
        public async discoverKeywordOpportunities(): Promise<{
    opportunities: {
        keyword: string
        currentArticles: number
        estimatedVolume: number
        difficulty: number
        potentialRank: number
        recommendedAction: string
    }[]
    totalOpportunities: number
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/automation/keyword-opportunities`)
            return await resp.json() as {
    opportunities: {
        keyword: string
        currentArticles: number
        estimatedVolume: number
        difficulty: number
        potentialRank: number
        recommendedAction: string
    }[]
    totalOpportunities: number
}
        }

        public async enhanceContentWithProducts(params: {
    articleId: number
    category?: string
}): Promise<{
    productsAdded: number
    estimatedRevenue: number
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/enhance-content-products`, JSON.stringify(params))
            return await resp.json() as {
    productsAdded: number
    estimatedRevenue: number
}
        }

        /**
         * Generates SEO-optimized content with affiliate product integration.
         */
        public async generateContent(params: GenerateContentRequest): Promise<GeneratedContent> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/generate-content`, JSON.stringify(params))
            return await resp.json() as GeneratedContent
        }

        /**
         * Generates comprehensive SEO performance report.
         */
        public async generateSEOReport(): Promise<SEOReport> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/automation/seo-report`)
            return await resp.json() as SEOReport
        }

        /**
         * Generates social media content from published articles.
         */
        public async generateSocialContent(params: GenerateSocialContentRequest): Promise<GenerateSocialContentResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/generate-social`, JSON.stringify(params))
            return await resp.json() as GenerateSocialContentResponse
        }

        /**
         * Generates and sends weekly performance digest.
         */
        public async generateWeeklyDigest(): Promise<WeeklyDigestResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/weekly-digest`)
            return await resp.json() as WeeklyDigestResponse
        }

        /**
         * Generates comprehensive weekly performance report.
         */
        public async generateWeeklyReport(): Promise<WeeklyReport> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/automation/weekly-report`)
            return await resp.json() as WeeklyReport
        }

        /**
         * Retrieves the content publishing schedule with revenue projections.
         */
        public async getContentSchedule(): Promise<GetScheduleResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/automation/content-schedule`)
            return await resp.json() as GetScheduleResponse
        }

        /**
         * Gets detailed health report for admin dashboard.
         */
        public async getLinkHealthReport(): Promise<{
    summary: LinkHealthReport
    brokenLinks: {
        id: number
        shortCode: string
        originalUrl: string
        consecutiveFailures: number
        lastError: string
    }[]
    slowLinks: {
        id: number
        shortCode: string
        averageResponseTime: number
    }[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/automation/link-health`)
            return await resp.json() as {
    summary: LinkHealthReport
    brokenLinks: {
        id: number
        shortCode: string
        originalUrl: string
        consecutiveFailures: number
        lastError: string
    }[]
    slowLinks: {
        id: number
        shortCode: string
        averageResponseTime: number
    }[]
}
        }

        /**
         * Gets all automation schedules for admin dashboard.
         */
        public async getSchedules(): Promise<GetSchedulesResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/automation/schedules`)
            return await resp.json() as GetSchedulesResponse
        }

        /**
         * Analyzes content performance and suggests optimization targets.
         */
        public async identifyOptimizationTargets(): Promise<{
    lowPerformingArticles: {
        articleId: number
        title: string
        currentRevenue: number
        potentialRevenue: number
        optimizationPriority: "high" | "medium" | "low"
    }[]
    keywordGaps: {
        keyword: string
        currentRank: number
        targetRank: number
        difficulty: number
    }[]
    affiliateOpportunities: {
        articleId: number
        title: string
        missingProducts: number
        potentialRevenue: number
    }[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/automation/optimization-targets`)
            return await resp.json() as {
    lowPerformingArticles: {
        articleId: number
        title: string
        currentRevenue: number
        potentialRevenue: number
        optimizationPriority: "high" | "medium" | "low"
    }[]
    keywordGaps: {
        keyword: string
        currentRank: number
        targetRank: number
        difficulty: number
    }[]
    affiliateOpportunities: {
        articleId: number
        title: string
        missingProducts: number
        potentialRevenue: number
    }[]
}
        }

        /**
         * Automatically implements selected optimizations.
         */
        public async implementOptimizations(params: ImplementOptimizationsRequest): Promise<{
    implemented: number
    failed: number
    estimatedImpact: number
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/implement-optimizations`, JSON.stringify(params))
            return await resp.json() as {
    implemented: number
    failed: number
    estimatedImpact: number
}
        }

        /**
         * Automatically implements revenue optimization actions.
         */
        public async implementRevenueOptimizations(params: {
    /**
     * Automatically implements revenue optimization actions.
     */
    actions: string[]
}): Promise<{
    /**
     * Automatically implements revenue optimization actions.
     */
    implemented: number

    /**
     * Automatically implements revenue optimization actions.
     */
    failed: number
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/implement-revenue-optimizations`, JSON.stringify(params))
            return await resp.json() as {
    /**
     * Automatically implements revenue optimization actions.
     */
    implemented: number

    /**
     * Automatically implements revenue optimization actions.
     */
    failed: number
}
        }

        /**
         * Ingests content ideas from Google Sheets and enqueues them for processing.
         */
        public async ingestFromSheets(params: IngestFromSheetsRequest): Promise<IngestFromSheetsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/ingest/sheets`, JSON.stringify(params))
            return await resp.json() as IngestFromSheetsResponse
        }

        /**
         * Optimizes individual article content using AI.
         */
        public async optimizeArticleContent(params: ContentOptimizationRequest): Promise<OptimizedContent> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/optimize-content`, JSON.stringify(params))
            return await resp.json() as OptimizedContent
        }

        /**
         * Processes scheduled content for publication.
         */
        public async processScheduledContent(): Promise<{
    /**
     * Processes scheduled content for publication.
     */
    processed: number

    /**
     * Processes scheduled content for publication.
     */
    failed: number
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/process-scheduled`)
            return await resp.json() as {
    /**
     * Processes scheduled content for publication.
     */
    processed: number

    /**
     * Processes scheduled content for publication.
     */
    failed: number
}
        }

        /**
         * Publishes scheduled social media posts.
         */
        public async publishScheduledPosts(): Promise<PublishPostsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/publish-social`)
            return await resp.json() as PublishPostsResponse
        }

        public async runContentPipeline(params: ContentPipelineRequest): Promise<ContentPipelineResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/content-pipeline`, JSON.stringify(params))
            return await resp.json() as ContentPipelineResponse
        }

        /**
         * Runs pending scheduled tasks.
         */
        public async runScheduledTasks(): Promise<RunTasksResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/run-tasks`)
            return await resp.json() as RunTasksResponse
        }

        /**
         * Schedules content generation and publishing with revenue optimization.
         */
        public async scheduleContent(params: ScheduleContentRequest): Promise<ScheduledContent> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/schedule-content`, JSON.stringify(params))
            return await resp.json() as ScheduledContent
        }

        public async scheduleContentGeneration(params: {
    schedule: "daily" | "weekly" | "monthly"
    topicsPerRun: number
    autoPublish?: boolean
    platforms?: ("medium" | "wordpress")[]
}): Promise<{
    scheduleName: string
    nextRun: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/schedule-content-generation`, JSON.stringify(params))
            return await resp.json() as {
    scheduleName: string
    nextRun: string
}
        }

        public async searchAmazonProducts(params: ProductSearchRequest): Promise<SearchProductsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/amazon/search`, JSON.stringify(params))
            return await resp.json() as SearchProductsResponse
        }

        /**
         * Sends automated email report (placeholder for email integration).
         */
        public async sendWeeklyReport(params: {
    /**
     * Sends automated email report (placeholder for email integration).
     */
    email: string
}): Promise<{
    /**
     * Sends automated email report (placeholder for email integration).
     */
    sent: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/send-report`, JSON.stringify(params))
            return await resp.json() as {
    /**
     * Sends automated email report (placeholder for email integration).
     */
    sent: boolean
}
        }

        public async syncAmazonProducts(params: {
    categories: string[]
}): Promise<ProductSyncResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/amazon/sync`, JSON.stringify(params))
            return await resp.json() as ProductSyncResponse
        }

        public async testSecrets(): Promise<SecretsTestResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/test-secrets`)
            return await resp.json() as SecretsTestResponse
        }

        /**
         * Tracks SEO performance for specific keywords.
         */
        public async trackKeyword(params: TrackKeywordRequest): Promise<{
    /**
     * Tracks SEO performance for specific keywords.
     */
    success: boolean

    /**
     * Tracks SEO performance for specific keywords.
     */
    keywordId: number
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/track-keyword`, JSON.stringify(params))
            return await resp.json() as {
    /**
     * Tracks SEO performance for specific keywords.
     */
    success: boolean

    /**
     * Tracks SEO performance for specific keywords.
     */
    keywordId: number
}
        }

        /**
         * Updates keyword rankings (would integrate with SEO tools in production).
         */
        public async updateKeywordRankings(): Promise<{
    /**
     * Updates keyword rankings (would integrate with SEO tools in production).
     */
    updated: number

    /**
     * Updates keyword rankings (would integrate with SEO tools in production).
     */
    failed: number
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/update-rankings`)
            return await resp.json() as {
    /**
     * Updates keyword rankings (would integrate with SEO tools in production).
     */
    updated: number

    /**
     * Updates keyword rankings (would integrate with SEO tools in production).
     */
    failed: number
}
        }
    }
}

export namespace content {
    export interface Article {
        id: number
        title: string
        slug: string
        content: string
        excerpt?: string
        featuredImageUrl?: string
        categoryId?: number
        authorName: string
        authorEmail: string
        published: boolean
        featured: boolean
        viewCount: number
        createdAt: string
        updatedAt: string
        category?: Category
        tags?: Tag[]
    }

    export interface Category {
        id: number
        name: string
        description?: string
        slug: string
        createdAt: string
    }

    export interface CreateArticleRequest {
        title: string
        content: string
        excerpt?: string
        featuredImageUrl?: string
        categoryId?: number
        authorName: string
        authorEmail: string
        published?: boolean
        featured?: boolean
        tagIds?: number[]
    }

    export interface CreateCategoryRequest {
        name: string
        description?: string
    }

    export interface CreateTagRequest {
        name: string
    }

    export interface GetPopularArticlesRequest {
        limit?: number
        days?: number
    }

    export interface ListArticlesRequest {
        limit?: number
        offset?: number
        categoryId?: number
        published?: boolean
        featured?: boolean
        search?: string
    }

    export interface ListArticlesResponse {
        articles: Article[]
        total: number
    }

    export interface ListCategoriesResponse {
        categories: Category[]
    }

    export interface ListTagsResponse {
        tags: Tag[]
    }

    export interface PublishToMediumRequest {
        articleId: number
        publishStatus?: "draft" | "public"
        canonicalUrl?: string
    }

    export interface PublishToMediumResponse {
        mediumPostId: string
        mediumUrl: string
        publishStatus: string
    }

    export interface PublishToWordPressRequest {
        articleId: number
        wordpressPostId?: number
        status?: "draft" | "publish"
    }

    export interface PublishToWordPressResponse {
        wordpressPostId: number
        wordpressUrl: string
        status: string
    }

    export interface SearchArticlesRequest {
        query: string
        limit?: number
        offset?: number
        categoryId?: number
    }

    export interface Tag {
        id: number
        name: string
        slug: string
        createdAt: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createArticle = this.createArticle.bind(this)
            this.createCategory = this.createCategory.bind(this)
            this.createTag = this.createTag.bind(this)
            this.deleteArticle = this.deleteArticle.bind(this)
            this.getArticle = this.getArticle.bind(this)
            this.getPopularArticles = this.getPopularArticles.bind(this)
            this.getRelatedArticles = this.getRelatedArticles.bind(this)
            this.listArticles = this.listArticles.bind(this)
            this.listCategories = this.listCategories.bind(this)
            this.listTags = this.listTags.bind(this)
            this.publishArticleToMedium = this.publishArticleToMedium.bind(this)
            this.publishToWordPress = this.publishToWordPress.bind(this)
            this.searchArticles = this.searchArticles.bind(this)
            this.updateArticle = this.updateArticle.bind(this)
        }

        /**
         * Creates a new article.
         */
        public async createArticle(params: CreateArticleRequest): Promise<Article> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/articles`, JSON.stringify(params))
            return await resp.json() as Article
        }

        /**
         * Creates a new category.
         */
        public async createCategory(params: CreateCategoryRequest): Promise<Category> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/categories`, JSON.stringify(params))
            return await resp.json() as Category
        }

        /**
         * Creates a new tag.
         */
        public async createTag(params: CreateTagRequest): Promise<Tag> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/tags`, JSON.stringify(params))
            return await resp.json() as Tag
        }

        /**
         * Deletes an article.
         */
        public async deleteArticle(id: number): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/articles/by-id/${encodeURIComponent(id)}`)
        }

        /**
         * Retrieves a single article by slug and increments view count.
         */
        public async getArticle(slug: string): Promise<Article> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/articles/by-slug/${encodeURIComponent(slug)}`)
            return await resp.json() as Article
        }

        /**
         * Retrieves the most popular articles based on view count within a specified time period.
         */
        public async getPopularArticles(params: GetPopularArticlesRequest): Promise<ListArticlesResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                days:  params.days === undefined ? undefined : String(params.days),
                limit: params.limit === undefined ? undefined : String(params.limit),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/articles/popular`, undefined, {query})
            return await resp.json() as ListArticlesResponse
        }

        /**
         * Retrieves articles related to the given article based on category and tags.
         */
        public async getRelatedArticles(slug: string, params: {
    limit?: number
}): Promise<ListArticlesResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/articles/by-slug/${encodeURIComponent(slug)}/related`, undefined, {query})
            return await resp.json() as ListArticlesResponse
        }

        /**
         * Retrieves all articles with optional filtering and pagination.
         */
        public async listArticles(params: ListArticlesRequest): Promise<ListArticlesResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                categoryId: params.categoryId === undefined ? undefined : String(params.categoryId),
                featured:   params.featured === undefined ? undefined : String(params.featured),
                limit:      params.limit === undefined ? undefined : String(params.limit),
                offset:     params.offset === undefined ? undefined : String(params.offset),
                published:  params.published === undefined ? undefined : String(params.published),
                search:     params.search,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/articles`, undefined, {query})
            return await resp.json() as ListArticlesResponse
        }

        /**
         * Retrieves all categories.
         */
        public async listCategories(): Promise<ListCategoriesResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/categories`)
            return await resp.json() as ListCategoriesResponse
        }

        /**
         * Retrieves all tags.
         */
        public async listTags(): Promise<ListTagsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/tags`)
            return await resp.json() as ListTagsResponse
        }

        /**
         * Publishes an article to Medium.
         */
        public async publishArticleToMedium(params: PublishToMediumRequest): Promise<PublishToMediumResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/content/publish-to-medium`, JSON.stringify(params))
            return await resp.json() as PublishToMediumResponse
        }

        /**
         * Publishes an article to WordPress.
         */
        public async publishToWordPress(params: PublishToWordPressRequest): Promise<PublishToWordPressResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/content/publish-to-wordpress`, JSON.stringify(params))
            return await resp.json() as PublishToWordPressResponse
        }

        /**
         * Searches articles by title, content, and tags with full-text search capabilities.
         */
        public async searchArticles(params: SearchArticlesRequest): Promise<ListArticlesResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                categoryId: params.categoryId === undefined ? undefined : String(params.categoryId),
                limit:      params.limit === undefined ? undefined : String(params.limit),
                offset:     params.offset === undefined ? undefined : String(params.offset),
                query:      params.query,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/articles/search`, undefined, {query})
            return await resp.json() as ListArticlesResponse
        }

        /**
         * Updates an existing article.
         */
        public async updateArticle(id: number, params: {
    title?: string
    content?: string
    excerpt?: string
    featuredImageUrl?: string
    categoryId?: number
    published?: boolean
    featured?: boolean
    tagIds?: number[]
    seoMeta?: any
    affiliateBlocks?: any
    wpPostId?: number
    mediumPostId?: string
}): Promise<Article> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/articles/by-id/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as Article
        }
    }
}

export namespace frontend {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.assets = this.assets.bind(this)
        }

        public async assets(path: string[]): Promise<void> {
            await this.baseClient.callTypedAPI("HEAD", `/frontend/${path.map(encodeURIComponent).join("/")}`)
        }
    }
}

export namespace newsletter {
    export interface SubscribeRequest {
        email: string
    }

    export interface SubscribeResponse {
        success: boolean
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.subscribe = this.subscribe.bind(this)
        }

        /**
         * Subscribes a user to the newsletter.
         */
        public async subscribe(params: SubscribeRequest): Promise<SubscribeResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/subscribe`, JSON.stringify(params))
            return await resp.json() as SubscribeResponse
        }
    }
}

export namespace seo {
    export interface HealthResponse {
        ok: boolean
        timestamp: string
        version: string
        services: {
            database: boolean
            ai: boolean
            affiliate: boolean
        }
    }

    export interface RobotsResponse {
        content: string
    }

    export interface SitemapResponse {
        xml: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.generateRobots = this.generateRobots.bind(this)
            this.generateSitemap = this.generateSitemap.bind(this)
            this.healthCheck = this.healthCheck.bind(this)
        }

        /**
         * Generates robots.txt for search engine crawling guidelines.
         */
        public async generateRobots(): Promise<RobotsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/robots.txt`)
            return await resp.json() as RobotsResponse
        }

        /**
         * Generates XML sitemap for SEO optimization.
         */
        public async generateSitemap(): Promise<SitemapResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/sitemap.xml`)
            return await resp.json() as SitemapResponse
        }

        /**
         * Health check endpoint for monitoring and deployment verification.
         */
        public async healthCheck(): Promise<HealthResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/healthz`)
            return await resp.json() as HealthResponse
        }
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | auth.AuthParams
  | Promise<auth.AuthParams | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "purelivingpro-ed2i-Generated-TS-Client (Encore/v1.52.3)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: auth.AuthParams | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
