-- Note: Cannot add foreign key constraints to tables in other databases
-- The following tables live in separate service databases:
-- - articles (content service)
-- - affiliate_links (affiliate service)
-- 
-- Foreign key relationships are maintained at the application level
-- The columns (published_article_id, affiliate_link_id, article_id) remain as regular columns