ALTER TABLE affiliate_links
  ADD COLUMN IF NOT EXISTS last_status TEXT,
  ADD COLUMN IF NOT EXISTS last_status_code INT,
  ADD COLUMN IF NOT EXISTS last_checked TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS ctr_14d NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS revenue_14d NUMERIC DEFAULT 0;
